server:
  port: 8095
spring:
  data:
    mongodb:
      auto-index-creation: true
      username: alibou
      password: alibou
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin